### ISSUE TITLE
Parsing exceptions with JSON format

### ISSUE THREAD

**Issue by slavafomin** [jaredhanson/deamdify#22]
Hello!

I were using this module in one of my projects.

I'm storing global configuration in `config.json` file and I require it from my scripts like this: `var config = require('config.json')`. When I do so, deamdify throws exceptions at me.

```
/node_modules/deamdify/node_modules/esprima/esprima.js:3734
            throw e;
                  ^
Error: Line 2: Unexpected token :
    at throwError (/node_modules/deamdify/node_modules/esprima/esprima.js:1846:21)
    at throwUnexpected (/node_modules/deamdify/node_modules/esprima/esprima.js:1904:9)
    at consumeSemicolon (/node_modules/deamdify/node_modules/esprima/esprima.js:1983:13)
    at parseStatement (/node_modules/deamdify/node_modules/esprima/esprima.js:3281:9)
...
```

**Comment by tbranyen** [comment]
Closed via 7e7e75ed520d0f28b36f4c4d3be1a440830860b3
